// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.11.4
// source: proto/store/store.proto

package go_micro_service_store_svc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ErrorMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ErrorMsg) Reset() {
	*x = ErrorMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_store_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMsg) ProtoMessage() {}

func (x *ErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_store_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMsg.ProtoReflect.Descriptor instead.
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return file_proto_store_store_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetByStoreIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreIds []int64 `protobuf:"varint,1,rep,packed,name=storeIds,proto3" json:"storeIds,omitempty"`
}

func (x *GetByStoreIdsRequest) Reset() {
	*x = GetByStoreIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_store_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByStoreIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByStoreIdsRequest) ProtoMessage() {}

func (x *GetByStoreIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_store_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByStoreIdsRequest.ProtoReflect.Descriptor instead.
func (*GetByStoreIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_store_store_proto_rawDescGZIP(), []int{1}
}

func (x *GetByStoreIdsRequest) GetStoreIds() []int64 {
	if x != nil {
		return x.StoreIds
	}
	return nil
}

type GetByStoreIdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreInfo []*StoreInfo `protobuf:"bytes,1,rep,name=storeInfo,proto3" json:"storeInfo,omitempty"`
}

func (x *GetByStoreIdsResponse) Reset() {
	*x = GetByStoreIdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_store_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByStoreIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByStoreIdsResponse) ProtoMessage() {}

func (x *GetByStoreIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_store_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByStoreIdsResponse.ProtoReflect.Descriptor instead.
func (*GetByStoreIdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_store_store_proto_rawDescGZIP(), []int{2}
}

func (x *GetByStoreIdsResponse) GetStoreInfo() []*StoreInfo {
	if x != nil {
		return x.StoreInfo
	}
	return nil
}

type SaveStoreInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreInfo *StoreInfo `protobuf:"bytes,1,opt,name=storeInfo,proto3" json:"storeInfo,omitempty"`
}

func (x *SaveStoreInfoRequest) Reset() {
	*x = SaveStoreInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_store_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveStoreInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStoreInfoRequest) ProtoMessage() {}

func (x *SaveStoreInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_store_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStoreInfoRequest.ProtoReflect.Descriptor instead.
func (*SaveStoreInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_store_store_proto_rawDescGZIP(), []int{3}
}

func (x *SaveStoreInfoRequest) GetStoreInfo() *StoreInfo {
	if x != nil {
		return x.StoreInfo
	}
	return nil
}

type StoreInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename   string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	BulkName   string `protobuf:"bytes,3,opt,name=bulkName,proto3" json:"bulkName,omitempty"`
	ObjectName string `protobuf:"bytes,4,opt,name=objectName,proto3" json:"objectName,omitempty"`
	Size       int64  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Type       int32  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *StoreInfo) Reset() {
	*x = StoreInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_store_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreInfo) ProtoMessage() {}

func (x *StoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_store_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreInfo.ProtoReflect.Descriptor instead.
func (*StoreInfo) Descriptor() ([]byte, []int) {
	return file_proto_store_store_proto_rawDescGZIP(), []int{4}
}

func (x *StoreInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoreInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StoreInfo) GetBulkName() string {
	if x != nil {
		return x.BulkName
	}
	return ""
}

func (x *StoreInfo) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *StoreInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StoreInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type SaveStoreInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ErrorMsg *ErrorMsg `protobuf:"bytes,999,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SaveStoreInfoResponse) Reset() {
	*x = SaveStoreInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_store_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveStoreInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStoreInfoResponse) ProtoMessage() {}

func (x *SaveStoreInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_store_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStoreInfoResponse.ProtoReflect.Descriptor instead.
func (*SaveStoreInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_store_store_proto_rawDescGZIP(), []int{5}
}

func (x *SaveStoreInfoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveStoreInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveStoreInfoResponse) GetErrorMsg() *ErrorMsg {
	if x != nil {
		return x.ErrorMsg
	}
	return nil
}

var File_proto_store_store_proto protoreflect.FileDescriptor

var file_proto_store_store_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x67, 0x6f, 0x2e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x5f, 0x73, 0x76, 0x63, 0x22, 0x1c, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x32, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x73, 0x22, 0x5c, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x43, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x76, 0x63,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x5b, 0x0a, 0x14, 0x53, 0x61, 0x76, 0x65, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a,
	0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x62, 0x75, 0x6c, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x75, 0x6c, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x7e, 0x0a, 0x15, 0x53, 0x61, 0x76, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x41, 0x0a,
	0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0xe7, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x32, 0xf7, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x76, 0x0a, 0x0d, 0x53, 0x61,
	0x76, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x2e, 0x67, 0x6f,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e,
	0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x76, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x49, 0x64, 0x73, 0x12, 0x30, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x76, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73,
	0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_store_store_proto_rawDescOnce sync.Once
	file_proto_store_store_proto_rawDescData = file_proto_store_store_proto_rawDesc
)

func file_proto_store_store_proto_rawDescGZIP() []byte {
	file_proto_store_store_proto_rawDescOnce.Do(func() {
		file_proto_store_store_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_store_store_proto_rawDescData)
	})
	return file_proto_store_store_proto_rawDescData
}

var file_proto_store_store_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_store_store_proto_goTypes = []interface{}{
	(*ErrorMsg)(nil),              // 0: go.micro.service.store_svc.ErrorMsg
	(*GetByStoreIdsRequest)(nil),  // 1: go.micro.service.store_svc.GetByStoreIdsRequest
	(*GetByStoreIdsResponse)(nil), // 2: go.micro.service.store_svc.GetByStoreIdsResponse
	(*SaveStoreInfoRequest)(nil),  // 3: go.micro.service.store_svc.SaveStoreInfoRequest
	(*StoreInfo)(nil),             // 4: go.micro.service.store_svc.StoreInfo
	(*SaveStoreInfoResponse)(nil), // 5: go.micro.service.store_svc.SaveStoreInfoResponse
}
var file_proto_store_store_proto_depIdxs = []int32{
	4, // 0: go.micro.service.store_svc.GetByStoreIdsResponse.storeInfo:type_name -> go.micro.service.store_svc.StoreInfo
	4, // 1: go.micro.service.store_svc.SaveStoreInfoRequest.storeInfo:type_name -> go.micro.service.store_svc.StoreInfo
	0, // 2: go.micro.service.store_svc.SaveStoreInfoResponse.errorMsg:type_name -> go.micro.service.store_svc.ErrorMsg
	3, // 3: go.micro.service.store_svc.Store.SaveStoreInfo:input_type -> go.micro.service.store_svc.SaveStoreInfoRequest
	1, // 4: go.micro.service.store_svc.Store.GetByStoreIds:input_type -> go.micro.service.store_svc.GetByStoreIdsRequest
	5, // 5: go.micro.service.store_svc.Store.SaveStoreInfo:output_type -> go.micro.service.store_svc.SaveStoreInfoResponse
	2, // 6: go.micro.service.store_svc.Store.GetByStoreIds:output_type -> go.micro.service.store_svc.GetByStoreIdsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_store_store_proto_init() }
func file_proto_store_store_proto_init() {
	if File_proto_store_store_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_store_store_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_store_store_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByStoreIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_store_store_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByStoreIdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_store_store_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveStoreInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_store_store_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_store_store_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveStoreInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_store_store_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_store_store_proto_goTypes,
		DependencyIndexes: file_proto_store_store_proto_depIdxs,
		MessageInfos:      file_proto_store_store_proto_msgTypes,
	}.Build()
	File_proto_store_store_proto = out.File
	file_proto_store_store_proto_rawDesc = nil
	file_proto_store_store_proto_goTypes = nil
	file_proto_store_store_proto_depIdxs = nil
}
